# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 3SB01 Rachanon's Web with Jekyll
# Description of the Site
description: >-
  รายวิชา 240-302 3SB01 Modern CMS for Website Generation
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/6210110297/3SB01-Rachanon-CMS-Web/master/pictures/copy_289612380.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/6210110297/3SB01-Rachanon-CMS-Web/master/pictures/avali_background__starbound__by_iamthecolonel_d7ln7n3-fullview.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 6210110297@psu.ac.th
facebook_username: Rachanon Khongchai
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  6210110297
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 


# Disqus
disqus-shortname: Rachanon

# Name of the Author
author-name: Rachanon Khongchai
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/6210110297/3SB01-Rachanon-CMS-Web/master/pictures/104491575_3163272333732871_7255461651550202179_n.jpg
# 60 Words About the Author
author-about: >-
  ยินดีตอนรับเข้าสู่ CMS Website ของ Rachanon เว็บไซต์สร้างขึ้นมาเพื่อศึกษารายวิชา 240-302 Advanced Computer Engineering Lab II หัวข้อ 3SB01 Modern CMS for Website Generation (อ.สุนทร)     **กรุณากด MORE เพิ่มดูข้อมูลเพิ่มเติม**
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/6210110297

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
